// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type LDAPUserPolicyAttachmentInitParameters struct {

	// (String) Name of policy to attach to user
	// Name of policy to attach to user
	// +crossplane:generate:reference:type=github.com/alekc/provider-minio/apis/policy/v1alpha1.Policy
	PolicyName *string `json:"policyName,omitempty" tf:"policy_name,omitempty"`

	// Reference to a Policy in policy to populate policyName.
	// +kubebuilder:validation:Optional
	PolicyNameRef *v1.Reference `json:"policyNameRef,omitempty" tf:"-"`

	// Selector for a Policy in policy to populate policyName.
	// +kubebuilder:validation:Optional
	PolicyNameSelector *v1.Selector `json:"policyNameSelector,omitempty" tf:"-"`

	// (String) The dn of user to attach policy to
	// The dn of user to attach policy to
	UserDn *string `json:"userDn,omitempty" tf:"user_dn,omitempty"`
}

type LDAPUserPolicyAttachmentObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of policy to attach to user
	// Name of policy to attach to user
	PolicyName *string `json:"policyName,omitempty" tf:"policy_name,omitempty"`

	// (String) The dn of user to attach policy to
	// The dn of user to attach policy to
	UserDn *string `json:"userDn,omitempty" tf:"user_dn,omitempty"`
}

type LDAPUserPolicyAttachmentParameters struct {

	// (String) Name of policy to attach to user
	// Name of policy to attach to user
	// +crossplane:generate:reference:type=github.com/alekc/provider-minio/apis/policy/v1alpha1.Policy
	// +kubebuilder:validation:Optional
	PolicyName *string `json:"policyName,omitempty" tf:"policy_name,omitempty"`

	// Reference to a Policy in policy to populate policyName.
	// +kubebuilder:validation:Optional
	PolicyNameRef *v1.Reference `json:"policyNameRef,omitempty" tf:"-"`

	// Selector for a Policy in policy to populate policyName.
	// +kubebuilder:validation:Optional
	PolicyNameSelector *v1.Selector `json:"policyNameSelector,omitempty" tf:"-"`

	// (String) The dn of user to attach policy to
	// The dn of user to attach policy to
	// +kubebuilder:validation:Optional
	UserDn *string `json:"userDn,omitempty" tf:"user_dn,omitempty"`
}

// LDAPUserPolicyAttachmentSpec defines the desired state of LDAPUserPolicyAttachment
type LDAPUserPolicyAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LDAPUserPolicyAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LDAPUserPolicyAttachmentInitParameters `json:"initProvider,omitempty"`
}

// LDAPUserPolicyAttachmentStatus defines the observed state of LDAPUserPolicyAttachment.
type LDAPUserPolicyAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LDAPUserPolicyAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LDAPUserPolicyAttachment is the Schema for the LDAPUserPolicyAttachments API. Attaches LDAP user to a policy. Can be used against both built-in and user-defined policies.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,minio}
type LDAPUserPolicyAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userDn) || (has(self.initProvider) && has(self.initProvider.userDn))",message="spec.forProvider.userDn is a required parameter"
	Spec   LDAPUserPolicyAttachmentSpec   `json:"spec"`
	Status LDAPUserPolicyAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LDAPUserPolicyAttachmentList contains a list of LDAPUserPolicyAttachments
type LDAPUserPolicyAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LDAPUserPolicyAttachment `json:"items"`
}

// Repository type metadata.
var (
	LDAPUserPolicyAttachment_Kind             = "LDAPUserPolicyAttachment"
	LDAPUserPolicyAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LDAPUserPolicyAttachment_Kind}.String()
	LDAPUserPolicyAttachment_KindAPIVersion   = LDAPUserPolicyAttachment_Kind + "." + CRDGroupVersion.String()
	LDAPUserPolicyAttachment_GroupVersionKind = CRDGroupVersion.WithKind(LDAPUserPolicyAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&LDAPUserPolicyAttachment{}, &LDAPUserPolicyAttachmentList{})
}
