#!/bin/bash
broken_doc_file=".work/aminueza/minio/docs/resources/accesskey.md"

# Check if the file already contains the patched header
if grep -q "page_title: \"Minio AccessKey Resource - terraform-provider-minio\"" "$broken_doc_file"; then
    echo "File is already patched. Skipping."
    exit 0
fi
echo "Patching $broken_doc_file"
echo '---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "Minio AccessKey Resource - terraform-provider-minio"
subcategory: ""
description: |-

---' | cat - $broken_doc_file > temp && mv temp $broken_doc_file