// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type VersioningConfigurationInitParameters struct {
	ExcludeFolders *bool `json:"excludeFolders,omitempty" tf:"exclude_folders,omitempty"`

	ExcludedPrefixes []*string `json:"excludedPrefixes,omitempty" tf:"excluded_prefixes,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type VersioningConfigurationObservation struct {
	ExcludeFolders *bool `json:"excludeFolders,omitempty" tf:"exclude_folders,omitempty"`

	ExcludedPrefixes []*string `json:"excludedPrefixes,omitempty" tf:"excluded_prefixes,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type VersioningConfigurationParameters struct {

	// +kubebuilder:validation:Optional
	ExcludeFolders *bool `json:"excludeFolders,omitempty" tf:"exclude_folders,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludedPrefixes []*string `json:"excludedPrefixes,omitempty" tf:"excluded_prefixes,omitempty"`

	// +kubebuilder:validation:Optional
	Status *string `json:"status" tf:"status,omitempty"`
}

type VersioningInitParameters struct {

	// Name of the bucket
	// +crossplane:generate:reference:type=github.com/alekc/provider-minio/apis/cluster/bucket/v1alpha1.Bucket
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in bucket to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v1.Reference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in bucket to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v1.Selector `json:"bucketSelector,omitempty" tf:"-"`

	VersioningConfiguration []VersioningConfigurationInitParameters `json:"versioningConfiguration,omitempty" tf:"versioning_configuration,omitempty"`
}

type VersioningObservation struct {

	// Name of the bucket
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	VersioningConfiguration []VersioningConfigurationObservation `json:"versioningConfiguration,omitempty" tf:"versioning_configuration,omitempty"`
}

type VersioningParameters struct {

	// Name of the bucket
	// +crossplane:generate:reference:type=github.com/alekc/provider-minio/apis/cluster/bucket/v1alpha1.Bucket
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in bucket to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v1.Reference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in bucket to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v1.Selector `json:"bucketSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	VersioningConfiguration []VersioningConfigurationParameters `json:"versioningConfiguration,omitempty" tf:"versioning_configuration,omitempty"`
}

// VersioningSpec defines the desired state of Versioning
type VersioningSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VersioningParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VersioningInitParameters `json:"initProvider,omitempty"`
}

// VersioningStatus defines the observed state of Versioning.
type VersioningStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VersioningObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Versioning is the Schema for the Versionings API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,minio}
type Versioning struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.versioningConfiguration) || (has(self.initProvider) && has(self.initProvider.versioningConfiguration))",message="spec.forProvider.versioningConfiguration is a required parameter"
	Spec   VersioningSpec   `json:"spec"`
	Status VersioningStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VersioningList contains a list of Versionings
type VersioningList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Versioning `json:"items"`
}

// Repository type metadata.
var (
	Versioning_Kind             = "Versioning"
	Versioning_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Versioning_Kind}.String()
	Versioning_KindAPIVersion   = Versioning_Kind + "." + CRDGroupVersion.String()
	Versioning_GroupVersionKind = CRDGroupVersion.WithKind(Versioning_Kind)
)

func init() {
	SchemeBuilder.Register(&Versioning{}, &VersioningList{})
}
