apiVersion: minio.alekc.dev/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: crossplane-provider-config
      namespace: default
      key: credentials
