apiVersion: v1
kind: Secret
metadata:
  name: crossplane-provider-config
  namespace: default
type: Opaque
stringData:
  credentials: |
    {
      "minio_server": "<MINIO_ENDPOINT:443>",
      "minio_user": "<MINIO_USER>",
      "minio_password": "<MINIO_PASSWORD>",
      "minio_ssl": "true"
    }
