apiVersion: iam.alekc.dev/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/user
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    forceDestroy: true
    name: test
    tags:
      tag-key: tag-value
  writeConnectionSecretToRef:
    name: test-user-secret
    namespace: default
