// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Bucket) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Notification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Policy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Replication) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Retention) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServerSideEncryption) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Versioning) Hub() {}
