apiVersion: bucket.minio.m.alekc.dev/v1alpha1
kind: Replication
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_b
  name: replication-in-b
  namespace: upbound-system
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: my_bucket_in_a
    rule:
    - deleteMarkerReplication: true
      deleteReplication: true
      existingObjectReplication: true
      metadataSync: true
      target:
      - accessKeySelector:
          matchLabels:
            testing.upbound.io/example-name: replication_in_b
        bandwidthLimit: 100M
        bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: my_bucket_in_b
        host: ${var.minio_server_b}
        secretKeySecretRef:
          key: attribute.secret_key
          name: example-iam-service-account
        secure: false

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_a
  name: replication-in-a
  namespace: upbound-system
spec:
  forProvider:
    name: ReplicationToMyBucketPolicy
    policy: ${data.minio_iam_policy_document.replication_policy.json}

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_b
  name: replication-in-b
  namespace: upbound-system
spec:
  forProvider:
    name: ReplicationToMyBucketPolicy
    policy: ${data.minio_iam_policy_document.replication_policy.json}
    provider: ${minio.deployment_b}

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_a
  name: replication-in-a
  namespace: upbound-system
spec:
  forProvider:
    targetUserSelector:
      matchLabels:
        testing.upbound.io/example-name: replication_in_a

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_b
  name: replication-in-b
  namespace: upbound-system
spec:
  forProvider:
    provider: ${minio.deployment_b}
    targetUserSelector:
      matchLabels:
        testing.upbound.io/example-name: replication_in_b

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_a
  name: replication-in-a
  namespace: upbound-system
spec:
  forProvider:
    forceDestroy: true
    name: my-user

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_b
  name: replication-in-b
  namespace: upbound-system
spec:
  forProvider:
    forceDestroy: true
    name: my-user
    provider: ${minio.deployment_b}

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: UserPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_a
  name: replication-in-a
  namespace: upbound-system
spec:
  forProvider:
    policyNameSelector:
      matchLabels:
        testing.upbound.io/example-name: replication_in_a
    userNameSelector:
      matchLabels:
        testing.upbound.io/example-name: replication_in_a

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: UserPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: replication_in_b
  name: replication-in-b
  namespace: upbound-system
spec:
  forProvider:
    policyNameSelector:
      matchLabels:
        testing.upbound.io/example-name: replication_in_b
    provider: ${minio.deployment_b}
    userNameSelector:
      matchLabels:
        testing.upbound.io/example-name: replication_in_b

---

apiVersion: bucket.minio.m.alekc.dev/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: my_bucket_in_a
  name: my-bucket-in-a
  namespace: upbound-system
spec:
  forProvider:
    bucket: my-bucket

---

apiVersion: bucket.minio.m.alekc.dev/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: bucket/v1alpha1/replication
  labels:
    testing.upbound.io/example-name: my_bucket_in_b
  name: my-bucket-in-b
  namespace: upbound-system
spec:
  forProvider:
    bucket: my-bucket
    provider: ${minio.deployment_b}
