apiVersion: iam.minio.alekc.dev/v1alpha1
kind: LDAPGroupPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/ldapgrouppolicyattachment
  labels:
    testing.upbound.io/example-name: developer
  name: developer
spec:
  forProvider:
    groupDn: CN=terraform-user,OU=Unit,DC=example,DC=com
    policyNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test_policy

---

apiVersion: iam.minio.alekc.dev/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/ldapgrouppolicyattachment
  labels:
    testing.upbound.io/example-name: test_policy
  name: test-policy
spec:
  forProvider:
    name: state-terraform-s3
    policy: |
      {
        "Version":"2012-10-17",
        "Statement": [
          {
            "Sid":"ListAllBucket",
            "Effect": "Allow",
            "Action": ["s3:PutObject"],
            "Principal":"*",
            "Resource": "arn:aws:s3:::state-terraform-s3/*"
          }
        ]
      }
