apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: GroupPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/grouppolicyattachment
  labels:
    testing.upbound.io/example-name: developer
  name: developer
  namespace: upbound-system
spec:
  forProvider:
    groupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: group
    policyNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test_policy

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/grouppolicyattachment
  labels:
    testing.upbound.io/example-name: developer
  name: developer
  namespace: upbound-system
spec:
  forProvider: {}

---

apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/grouppolicyattachment
  labels:
    testing.upbound.io/example-name: test_policy
  name: test-policy
  namespace: upbound-system
spec:
  forProvider:
    policy: |
      {
        "Version":"2012-10-17",
        "Statement": [
          {
            "Sid":"ListAllBucket",
            "Effect": "Allow",
            "Action": ["s3:PutObject"],
            "Principal":"*",
            "Resource": "arn:aws:s3:::state-terraform-s3/*"
          }
        ]
      }
