apiVersion: iam.minio.m.alekc.dev/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/group
  labels:
    testing.upbound.io/example-name: developer
  name: developer
  namespace: upbound-system
spec:
  forProvider: {}
