name: Build
on:
  pull_request: { }
  push:
    branches:
      - ci
      - master

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Determine Go version from go.mod
        run: echo "GO_REQUIRED_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run build
        run:
          make submodules
          make xpkg.build.provider-minio